
const MATS=[{n:'碳素结构钢',i:[{n:'Q235 (A3钢)',de:7.85},{n:'45#钢',de:7.85},{n:'40Cr',de:7.85},{n:'65Mn',de:7.85}]},{n:'合金钢',i:[{n:'Cr12 (模具钢)',de:7.85},{n:'Cr12MoV',de:7.85},{n:'SKD11',de:7.85},{n:'DC53',de:7.85},{n:'H13',de:7.85}]},{n:'不锈钢',i:[{n:'304',de:7.93},{n:'316',de:7.98},{n:'410',de:7.75},{n:'420',de:7.75},{n:'430',de:7.70}]},{n:'铝合金',i:[{n:'6061',de:2.70},{n:'6063',de:2.69},{n:'7075',de:2.81},{n:'5052',de:2.68},{n:'LY12',de:2.78}]},{n:'铜合金',i:[{n:'黄铜 H62',de:8.43},{n:'黄铜 H65',de:8.47},{n:'紫铜 T2',de:8.96},{n:'青铜 QSn6.5',de:8.80},{n:'铍铜 QBe2',de:8.23}]},{n:'钛合金',i:[{n:'TC4',de:4.43},{n:'TA2',de:4.51}]},{n:'工程塑料',i:[{n:'尼龙 PA6',de:1.14},{n:'PA66',de:1.15},{n:'POM',de:1.41},{n:'ABS',de:1.05},{n:'PTFE',de:2.20},{n:'PC',de:1.20}]},{n:'其他',i:[{n:'铸钢',de:7.80},{n:'灰铸铁',de:7.20},{n:'球墨铸铁',de:7.30}]}];
const PROCS=[{n:'加工中心',i:[{n:'三轴 (≤300mm)',p:60},{n:'三轴 (1~2m)',p:80},{n:'三轴 (>2m)',p:100},{n:'四轴',p:120},{n:'五轴',p:200},{n:'卧式加工中心',p:150}]},{n:'数控车床',i:[{n:'排刀式数控车',p:50},{n:'刀塔式数控车',p:60},{n:'车铣复合',p:80}]},{n:'普通机床',i:[{n:'手摇车床',p:40},{n:'普通车床',p:45},{n:'手摇钻床',p:35},{n:'摇臂钻',p:40},{n:'镗床',p:60},{n:'坐标镗',p:80},{n:'牛头刨',p:50}]},{n:'磨床',i:[{n:'精密平面磨',p:200},{n:'大水磨',p:80},{n:'外圆磨',p:60},{n:'内圆磨',p:60}]},{n:'特种加工',i:[{n:'线切割',p:0.005},{n:'电火花',p:50},{n:'激光切割',p:35}]},{n:'表面处理',i:[{n:'镀铬',p:19},{n:'镀锌',p:3},{n:'阳极氧化 (本色)',p:4},{n:'阳极氧化 (喷砂)',p:8},{n:'镀镍',p:5},{n:'喷漆',p:5}]},{n:'热处理',i:[{n:'淬火',p:5},{n:'回火',p:3},{n:'氮化',p:8},{n:'真空加硬',p:10}]},{n:'钣金/冲压',i:[{n:'冲压',p:2},{n:'折弯',p:3},{n:'剪板',p:2},{n:'焊接',p:20}]},{n:'钻孔/攻牙',i:[{n:'钻孔',p:0.5},{n:'攻牙',p:0.5}]}];
let S={lg:false,cu:null,tab:'calc',a:'',b:'',date:'',no:'',shp:'square',l:'',w:'',h:'',d:'',h2:'',mt:null,mp:'',q:1,pr:[],dl:'self',df:'',tx:'no',fe:[]};

var bc=null,bxCtx=null,bW=0,bH=0,bubbles=[],bubbleAnimId=null;
function initBubbles(){bc=document.getElementById('bubbleCanvas');if(!bc)return;
bxCtx=bc.getContext('2d');function rs(){bW=bc.width=window.innerWidth;bH=bc.height=window.innerHeight}
rs();window.addEventListener('resize',rs);
bubbles=[];for(var i=0;i<30;i++){bubbles.push({
x:Math.random()*bW,y:Math.random()*bH,
r:5+Math.random()*17,s:.3+Math.random()*.4,
vy:-(.1+Math.random()*.2),vx:(Math.random()-.5)*.3
})}startBubbles()}
function startBubbles(){if(!bxCtx)return;function dr(){bxCtx.clearRect(0,0,bW,bH);
bubbles.forEach(function(p){p.y+=p.vy;p.x+=p.vx;
if(p.y<-p.r||p.x<-p.r||p.x>bW+p.r){p.y=bH+p.r;p.x=Math.random()*bW}
bxCtx.globalAlpha=p.s;bxCtx.beginPath();
bxCtx.arc(p.x,p.y,p.r,0,Math.PI*2);
bxCtx.fillStyle='#2d7aff';bxCtx.fill()});
bxCtx.globalAlpha=1;bubbleAnimId=requestAnimationFrame(dr)}
bubbleAnimId=requestAnimationFrame(dr)}
function stopBubbles(){if(bubbleAnimId){cancelAnimationFrame(bubbleAnimId);bubbleAnimId=null}
if(bxCtx){bxCtx.clearRect(0,0,bW,bH)}}

// CloudBase initialization
let cApp=null,cDb=null;
function initCloud(){try{if(typeof cloudbase==='undefined')return false;cApp=cloudbase.init({env:'gongjia-d7gndma00cff857eb'});cDb=cApp.database();return true}catch(e){console.warn('CloudBase:',e);return false}}
function ensureCloud(){if(!cApp)initCloud()}
function cloudSyncUsers(data){ensureCloud();if(!cDb)return;try{cDb.collection('users').doc('main').set({data:JSON.parse(JSON.stringify(data)),updatedAt:new Date()})}catch(e){}}
function cloudSyncOrders(data){ensureCloud();if(!cDb)return;try{cDb.collection('orders').doc('all').set({data:JSON.parse(JSON.stringify(data)),updatedAt:new Date()})}catch(e){}}
async function cloudPullOnLogin(){ensureCloud();if(!cDb)return;try{let ur=cDb.collection('users').doc('main');let uRes=await ur.get();if(uRes.data&&uRes.data.data){let rU=uRes.data.data,lU=lu();for(let k in rU){if(!lU[k])lU[k]=rU[k]};su(lU)}let or=cDb.collection('orders').doc('all');let oRes=await or.get();if(oRes.data&&oRes.data.data){let rO=oRes.data.data,lO=lo();if(rO.length>lO.length){let merged=[...rO];lO.forEach(o=>{if(!merged.find(x=>x.orderId===o.orderId))merged.push(o)});so(merged)}}}catch(e){}}
let hS='',hP=1,pS=6;
function gn(){const d=new Date();return d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[Math.floor(Math.random()*26)]+'ABCDEFGHIJKLMNOPQRSTUVWXYZ'[Math.floor(Math.random()*26)]}
function gu(){let n='';for(let i=0;i<5;i++)n+=Math.floor(Math.random()*10);const c='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(let i=0;i<2;i++)n+=c[Math.floor(Math.random()*26)];return n}
function lu(){return JSON.parse(localStorage.getItem('u')||'{}')}function su(x){localStorage.setItem('u',JSON.stringify(x));cloudSyncUsers(x)}
function lo(){return JSON.parse(localStorage.getItem('o')||'[]')}function so(x){localStorage.setItem('o',JSON.stringify(x));cloudSyncOrders(x)}
function la(){return localStorage.getItem('au')||null}
function td(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function cw(){if(!S.mt)return 0;let v=0;if(S.shp==='square')v=(parseFloat(S.l)||0)*(parseFloat(S.w)||0)*(parseFloat(S.h)||0);else v=Math.PI*((parseFloat(S.d)||0)/2)**2*(parseFloat(S.h2)||0);return(v/1000)*S.mt.de/1000}
function cum(){return cw()*(parseFloat(S.mp)||0)}function ctm(){return cum()*(parseInt(S.q)||1)}
function cpp(p){let h=parseFloat(p.h)||0;if(p.u==='秒')h/=3600;else if(p.u==='分')h/=60;return h*(parseFloat(p.p)||0)}
function ctp(){return S.pr.reduce((s,p)=>s+cpp(p),0)*(parseInt(S.q)||1)}
function cfe(){return S.fe.reduce((s,f)=>s+(parseFloat(f.a)||0),0)}
function ctot(){let b=ctm()+ctp()+cfe();if(S.dl==='send')b+=parseFloat(S.df)||0;if(S.tx==='yes')b*=1.13;return b}
function gd(){return{orderId:S.no,clientName:S.a,ourCompany:S.b,date:S.date,material:S.mt,materialPrice:S.mp,quantity:S.q,shape:S.shp,dimensions:{l:S.l,w:S.w,h:S.h,d:S.d,h2:S.h2},processes:S.pr.map(p=>({procName:p.n,hours:p.h,unit:p.u,price:p.p})),delivery:S.dl,shippingFee:S.df,taxIncluded:S.tx==='yes',extraItems:S.fe.map(f=>({name:f.n,fee:f.a})),totalPrice:ctot(),saveTime:new Date().toISOString()}}
function sto(o){let os=lo(),i=os.findIndex(x=>x.orderId===o.orderId);if(i>=0){if(JSON.stringify(o)===JSON.stringify(os[i])){tst('内容未变化','warn');return false}let b=o.orderId.replace(/\(\d+\)$/,''),mv=0;os.forEach(x=>{let m=x.orderId.match(new RegExp('^'+b.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\((\\d+)\\)$'));if(m)mv=Math.max(mv,parseInt(m[1]))});o.orderId=b+'('+(mv+1)+')'}os.push(o);so(os);return true}
function tst(m,t){const e=document.getElementById('toast');if(!e)return;e.textContent=m;e.className='toast'+(t?' '+t:'');e.style.display='block';clearTimeout(window._tt);window._tt=setTimeout(()=>{e.style.display='none'},2500)}
function scf(msg,y,n){const o=document.getElementById('cvr'),m=document.getElementById('cMsg'),ok=document.getElementById('cYes'),no=document.getElementById('cNo');m.textContent=msg;o.classList.add('on');const cl=()=>{o.classList.remove('on');ok.onclick=null;no.onclick=null};ok.onclick=()=>{cl();if(y)y()};no.onclick=()=>{cl();if(n)n()}}
function es(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
const ap=document.getElementById('app');
function r(){if(!S.lg){rL();pullCloudData();return}rA()}

// 登录页加载时从云端拉取数据合并到本地
async function pullCloudData(){ensureCloud();if(!cDb)return;try{let ur=cDb.collection('users').doc('main');let uRes=await ur.get();if(uRes.data&&uRes.data.data){let rU=uRes.data.data,lU=lu();let changed=false;for(let k in rU){if(!lU[k]){lU[k]=rU[k];changed=true}}if(changed)su(lU)}let or=cDb.collection('orders').doc('all');let oRes=await or.get();if(oRes.data&&oRes.data.data){let rO=oRes.data.data,lO=lo();if(rO.length>lO.length){let merged=[...rO];lO.forEach(o=>{if(!merged.find(x=>x.orderId===o.orderId))merged.push(o)});so(merged)}}}catch(e){}}

function rL(){const au=la();initBubbles()
ap.innerHTML='<div class="login-wrap"><div style="width:100%;padding:10px 0;text-align:center"><img src="数智工价/图标黑.png" style="height:120px"><div class="login-title">数智工价</div><div class="login-version">V2.2.2</div></div><div class="sub">用算法重新定义报价逻辑</div><div class="login-card"><div class="f"><label>UID</label><div class="iw"><input type="text" id="uidI" placeholder="请输入UID"></div></div><div class="f"><label>密码</label><div class="iw"><input type="password" id="pwdI" placeholder="输入密码"><button class="pwt" id="pwdT">👁</button></div></div><div class="lerr" id="lErr"></div><button class="lbtn" id="lBtn">登 录</button><div class="auto"><input type="checkbox" id="autoC"><label for="autoC">下次自动登录</label></div><div class="lreg" id="goR">注册新账号</div></div><div style="text-align:center;margin-top:16px;font-size:11px;color:#888">本项目由<img src="数智工价/logo.png" id="lgImgLogo" style="height:35px;vertical-align:middle;margin:-3px 3px 0">项目小组制作</div></div>'
document.getElementById('lBtn').onclick=doL;document.getElementById('goR').onclick=rR;document.getElementById('pwdI').addEventListener('keydown',e=>{if(e.key==='Enter')doL()});const pt=document.getElementById('pwdT');if(pt)pt.onclick=()=>{const i=document.getElementById('pwdI');if(i.type==='password'){i.type='text';pt.textContent='🙈'}else{i.type='password';pt.textContent='👁'}}
}
function doL(){const u=document.getElementById('uidI').value.trim().toUpperCase(),p=document.getElementById('pwdI').value,e=document.getElementById('lErr');if(!u||!p){e.textContent=' ';return}const us=lu();if(!us[u]){e.textContent='UID错误';return}if(us[u].pwd!==p){e.textContent='密码错误';return}e.textContent='';S.cu=us[u];S.cu.uid=u;if(document.getElementById('autoC').checked)localStorage.setItem('au',u);else localStorage.removeItem('au');S.lg=true;r();cloudPullOnLogin()}
function rR(){let nu=gu();initBubbles();setTimeout(genCap,50)
ap.innerHTML='<div class="login-wrap"><div style="width:100%;padding:10px 0;text-align:center"><img src="数智工价/图标黑.png" style="height:120px"><div class="login-title">数智工价</div><div class="login-version">V2.2.2</div></div><div class="sub">注册新账号</div><div class="reg-card"><div class="f"><label>您的UID</label><div class="uid-box" id="ru">'+nu+'<button class="cb" id="rc">📋</button></div><div style="font-size:12px;color:#999;text-align:center;margin-top:4px">请妥善保管此UID，登录时使用</div></div><div class="f"><label>设置密码</label><div class="iw"><input type="password" id="rp" placeholder="输入密码（至少6位，字母/数字）"><button class="pwt" id="rpT">👁</button></div></div><div class="f"><label>确认密码</label><div class="iw"><input type="password" id="rcp" placeholder="请再次输入密码"><button class="pwt" id="rcpT">👁</button></div></div><div class="f"><div style="display:flex;gap:8px;align-items:center;margin-top:2px"><div style="font-size:13px;font-weight:600;background:#f0f4ff;padding:8px 14px;border-radius:9px;white-space:nowrap;color:#333" id="capQ"></div><input id="capI" type="text" placeholder="输入答案" style="flex:1;min-width:0;padding:8px 10px"><span onclick="genCap()" style="font-size:13px;color:#2d7aff;cursor:pointer;flex-shrink:0">🔄</span></div><div class="lerr" id="capE" style="min-height:16px;font-size:11px"></div></div><div class="lerr" id="rErr"></div><button class="rbtn" id="rBtn">注 册</button><div class="lreg" id="goL">返回登录</div></div><div style="text-align:center;margin-top:16px;font-size:11px;color:#888">本项目由<img src="数智工价/logo.png" id="lgImgLogo" style="height:35px;vertical-align:middle;margin:-3px 3px 0">项目小组制作</div></div>'
document.getElementById('goL').onclick=rL;document.getElementById('rc').onclick=()=>{navigator.clipboard.writeText(nu).then(()=>tst('已复制UID','ok'))};document.querySelectorAll('#rpT,#rcpT').forEach(el=>{el.onclick=function(){const i=this.parentElement.querySelector('input');if(i.type==='password'){i.type='text';this.textContent='🙈'}else{i.type='password';this.textContent='👁'}}})
document.getElementById('rBtn').onclick=()=>{var capE=document.getElementById('capE');if(parseInt(document.getElementById('capI').value)!==capAns){capE.textContent='验证码错误';genCap();return}else capE.textContent='';const p=document.getElementById('rp').value,cp=document.getElementById('rcp').value,err=document.getElementById('rErr');if(!/^[A-Za-z0-9]{6,}$/.test(p)){err.textContent='密码至少6位，字母/数字';return}if(p!==cp){err.textContent='两次密码不一致';return}const us=lu();if(us[nu]){nu=gu();document.getElementById('ru').innerHTML=nu+'<button class="cb" id="rc">📋</button>';document.getElementById('rc').onclick=()=>{navigator.clipboard.writeText(nu).then(()=>tst('已复制UID','ok'))};err.textContent='';return}us[nu]={pwd:p,uid:nu,name:nu};su(us);tst('注册成功！','ok');rL()}}

function rA(){stopBubbles();if(!S.no)S.no=gn();if(!S.date)S.date=td()
let ca=S.tab==='calc'?'active':'',hi=S.tab==='history'?'active':'',pr=S.tab==='profile'?'active':''
ap.innerHTML='<div class="page '+ca+'" id="pCalc">'+(S.tab==='calc'?rC():'')+'</div><div class="page '+hi+'" id="pHist">'+(S.tab==='history'?rH():'')+'</div><div class="page '+pr+'" id="pProf">'+(S.tab==='profile'?rP():'')+'</div><div class="tab-bar"><div class="ti '+ca+'" data-t="calc"><svg viewBox="0 0 24 24"><path d="M19.5 3.5L18 2l-1.5 1.5L15 2l-1.5 1.5L12 2l-1.5 1.5L9 2 7.5 3.5 6 2 4.5 3.5 3 2v20l1.5-1.5L6 22l1.5-1.5L9 22l1.5-1.5L12 22l1.5-1.5L15 22l1.5-1.5L18 22l1.5-1.5L21 22V2l-1.5 1.5zM19 19H5V5h14v14z"/></svg><span>工价计算</span></div><div class="ti '+hi+'" data-t="history"><svg viewBox="0 0 24 24"><path d="M4 2v20h16V2H4zm14 18H6V4h12v16zm-2-8H8v-2h8v2zm0-4H8V6h8v2zm0 8H8v-2h8v2z"/></svg><span>历史订单</span></div><div class="ti '+pr+'" data-t="profile"><svg viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg><span>我的</span></div></div>'
document.querySelectorAll('.ti').forEach(el=>{el.onclick=function(){S.tab=this.dataset.t;rA()}})
setTimeout(()=>{if(S.tab==='calc')initC();if(S.tab==='history'){document.getElementById('hBtn').onclick=()=>{hS=document.getElementById('hSch').value;hP=1;rHL()};rHL()}if(S.tab==='profile')initP()},50)}

function buildMT(){let h='';MATS.forEach((g,gi)=>{h+='<div><div class="tcat" onclick="togM('+gi+')"><span class="arr" id="arrM'+gi+'">▶</span> '+g.n+'</div><div class="tits" id="tm'+gi+'">';g.i.forEach(it=>{h+='<div class="tit" onclick="selM(\''+gi+'|'+it.n+'|'+it.de+'\')"><input type="radio" name="mR"> <span>'+it.n+' ('+it.de+'g/cm³)</span></div>'});h+='</div></div>'});return h}
function selM(v){const p=v.split('|');S.mt={n:p[1],de:parseFloat(p[2])};const md=document.getElementById('mDisp');if(md)md.value=p[1]+' ('+p[2]+'g/cm³)';upQ()}
function togM(i){const e=document.getElementById('tm'+i),a=document.getElementById('arrM'+i);if(e){e.classList.toggle('on');if(a)a.classList.toggle('on')}}

function rC(){return'<div class="phdr"><div class="fw"><input type="text" id="pA" placeholder="甲方名称"><div class="ahint" id="ahA"></div><div class="nerr" id="nA"></div></div><div class="fw"><input type="text" id="pB" placeholder="乙方名称"><div class="ahint" id="ahB"></div><div class="nerr" id="nB"></div></div></div>'+
'<div class="card"><div class="ct">材料成本</div><div class="sg"><button class="active" id="shS">方形</button><button id="shC">圆柱形</button></div><div id="sqDims"><div class="sg" style="margin-bottom:12px"><div style="flex:1"><div style="font-size:10px;color:#999;margin-bottom:2px">长(mm)</div><input type="number" id="dL" placeholder="0" min="0"></div><div style="flex:1"><div style="font-size:10px;color:#999;margin-bottom:2px">宽(mm)</div><input type="number" id="dW" placeholder="0" min="0"></div><div style="flex:1"><div style="font-size:10px;color:#999;margin-bottom:2px">高(mm)</div><input type="number" id="dH" placeholder="0" min="0"></div></div></div><div id="cylDims" class="hidden"><div class="sg" style="margin-bottom:12px"><div style="flex:1"><div style="font-size:10px;color:#999;margin-bottom:2px">直径(mm)</div><input type="number" id="dD" placeholder="0" min="0"></div><div style="flex:1"><div style="font-size:10px;color:#999;margin-bottom:2px">高(mm)</div><input type="number" id="dH2" placeholder="0" min="0"></div></div></div>'+
'<div class="mtree"><div class="stree"><input type="text" id="mSch" placeholder="搜索材料..."></div><div id="mBody">'+buildMT()+'</div></div>'+
'<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px"><div><div style="font-size:10px;color:#999">已选材料</div><input type="text" id="mDisp" readonly></div><div><div style="font-size:10px;color:#999">单价(元/kg)</div><input type="number" id="mP" placeholder="0" min="0" step="0.1"></div></div>'+
'<div style="margin-top:10px"><div style="font-size:10px;color:#999">数量</div><input type="number" id="qty" value="1" min="1" step="1"></div>'+
'<div class="mr"><div><div class="ml">单重</div><div class="mv" id="dWt">0.000 kg</div></div><div><div class="ml">单个成本</div><div class="mv" id="dUC">0.00 元</div></div><div><div class="ml">总材料成本</div><div class="mv" id="dTC">0.00 元</div></div><div><div class="ml">数量</div><div class="mv" id="dQ">1 件</div></div></div></div>'+
'<div class="card"><div class="ct">加工工序</div><div style="overflow-x:auto"><table class="ptab"><thead><tr><th>序号</th><th>工艺</th><th>工时</th><th>单位</th><th>单价</th><th>金额</th><th></th></tr></thead><tbody id="prB"></tbody></table></div><button class="dsbtn" id="addPr">+ 增加工序</button></div>'+
'<div class="card"><div class="ct">其他费用</div><div style="margin-bottom:10px"><div style="font-size:10px;color:#999;margin-bottom:4px">取货方式</div><div class="sg"><button class="active" id="delSelf">自提</button><button id="delSend">运送</button></div><div id="dfW" class="hidden"><div style="font-size:10px;color:#999;margin-bottom:4px">运费(元)</div><input type="number" id="dF" placeholder="0" min="0" step="1"></div></div>'+
'<div style="margin-bottom:10px"><div style="font-size:10px;color:#999;margin-bottom:4px">含税(13%)</div><div class="sg"><button class="active" id="taxNo">否</button><button id="taxYes">是</button></div></div><div id="feeL"></div><button class="dsbtn" id="addFee">+ 增加其他费用</button></div>'+
'<div class="total-display"><span>总价（所有零件）</span><span class="tdv">¥ 0.00</span></div>'+
'<div class="card" style="margin-bottom:0"><div class="ct">报价单预览</div><div class="qp" id="qPv"><h2>工价计算器报价单</h2><hr><div class="qr"><span>甲方</span><span>—</span></div><div class="qr"><span>乙方</span><span>—</span></div><div class="qr"><span>编号</span><span>—</span></div><div class="qr"><span>日期</span><span>—</span></div><hr><div class="qs">📦 材料费用</div><div class="qr"><span>暂无数据</span><span></span></div></div></div>'+
'<div class="action-bar"><button class="btn-p" id="sBtn">💾 一键保存</button><button class="btn-o" id="cBtn">📋 一键复制</button><button class="btn-d" id="dBtn">🗑️ 一键清除</button></div>'}

function upQ(){const w=cw(),uc=cum(),tc=ctm();const dw=document.getElementById('dWt'),du=document.getElementById('dUC'),dt=document.getElementById('dTC'),dq=document.getElementById('dQ'),tdv=document.querySelector('.tdv');if(dw)dw.textContent=w.toFixed(3)+' kg';if(du)du.textContent=uc.toFixed(2)+' 元';if(dt)dt.textContent=tc.toFixed(2)+' 元';if(dq)dq.textContent=S.q+' 件';if(tdv)tdv.textContent='¥ '+ctot().toFixed(2);const qp=document.getElementById('qPv');if(qp)qp.innerHTML=bQ()}
function bQ(){return'<h2>工价计算器报价单</h2><hr><div class="qr"><span>甲方</span><span>'+(S.a||'—')+'</span></div><div class="qr"><span>乙方</span><span>'+(S.b||'—')+'</span></div><div class="qr"><span>编号</span><span>'+S.no+'</span></div><div class="qr"><span>日期</span><span>'+S.date+'</span></div><hr><div class="qs">📦 材料费用</div>'+(S.mt?'<div class="qr"><span>材料类型</span><span>'+S.mt.n+' ('+S.mt.de+'g/cm³)</span></div>':'')+'<div class="qr"><span>尺寸</span><span>'+(S.shp==='square'?'长'+S.l+'mm×宽'+S.w+'mm×高'+S.h+'mm':'直径'+S.d+'mm×高'+S.h2+'mm')+'</span></div><div class="qr"><span>数量</span><span>'+S.q+' 件</span></div><div class="qr"><span>单价</span><span>'+parseFloat(S.mp).toFixed(2)+' 元/kg</span></div><div class="qr"><span>单重</span><span>'+cw().toFixed(3)+'kg</span></div><div class="qr"><span>材料总成本</span><span>'+ctm().toFixed(2)+' 元</span></div><hr><div class="qs">⚙️ 加工工序</div>'+(S.pr.length===0?'<div class="qr"><span>无</span><span></span></div>':S.pr.map(p=>'<div class="qr"><span>'+(p.n||'未选择')+'</span><span>'+(p.h||0)+'h×'+parseFloat(p.p||0).toFixed(2)+'='+cpp(p).toFixed(2)+'元</span></div>').join(''))+'<hr><div class="qs">💰 其他费用</div>'+(S.dl==='send'?'<div class="qr"><span>运费</span><span>'+parseFloat(S.df).toFixed(2)+' 元</span></div>':'')+S.fe.filter(f=>f.n).map(f=>'<div class="qr"><span>'+(f.n||'')+'</span><span>'+parseFloat(f.a||0).toFixed(2)+' 元</span></div>').join('')+'<div class="qr"><span>税</span><span>'+(S.tx==='yes'?'已含13%增值税':'未含税')+'</span></div><hr><div class="qt">总价: ¥ <span>'+ctot().toFixed(2)+'</span></div><div class="qfb">本报价单由「工价计算器」生成，仅供参考</div>'}

function initC(){const ms=document.getElementById('mSch');if(ms)ms.oninput=function(){const kw=this.value.toLowerCase();let h='';MATS.forEach((g,gi)=>{let its=g.i;if(kw)its=its.filter(it=>it.n.toLowerCase().includes(kw));if(its.length===0)return;h+='<div><div class="tcat" onclick="togM('+gi+')"><span class="arr" id="arrM'+gi+'">▶</span> '+g.n+'</div><div class="tits" id="tm'+gi+'">';its.forEach(it=>{h+='<div class="tit" onclick="selM(\''+gi+'|'+it.n+'|'+it.de+'\')"><input type="radio" name="mR"> <span>'+it.n+' ('+it.de+'g/cm³)</span></div>'});h+='</div></div>'});document.getElementById('mBody').innerHTML=h}
document.getElementById('shS').onclick=()=>{S.shp='square';document.getElementById('sqDims').classList.remove('hidden');document.getElementById('cylDims').classList.add('hidden');document.getElementById('shS').classList.add('active');document.getElementById('shC').classList.remove('active');upQ()}
document.getElementById('shC').onclick=()=>{S.shp='cylinder';document.getElementById('sqDims').classList.add('hidden');document.getElementById('cylDims').classList.remove('hidden');document.getElementById('shC').classList.add('active');document.getElementById('shS').classList.remove('active');upQ()}
document.getElementById('delSelf').onclick=()=>{S.dl='self';document.getElementById('dfW').classList.add('hidden');document.getElementById('delSelf').classList.add('active');document.getElementById('delSend').classList.remove('active');upQ()}
document.getElementById('delSend').onclick=()=>{S.dl='send';document.getElementById('dfW').classList.remove('hidden');document.getElementById('delSend').classList.add('active');document.getElementById('delSelf').classList.remove('active');upQ()}
document.getElementById('taxNo').onclick=()=>{S.tx='no';document.getElementById('taxNo').classList.add('active');document.getElementById('taxYes').classList.remove('active');upQ()}
document.getElementById('taxYes').onclick=()=>{S.tx='yes';document.getElementById('taxYes').classList.add('active');document.getElementById('taxNo').classList.remove('active');upQ()}
;['dL','dW','dH','dD','dH2'].forEach(id=>{const e=document.getElementById(id);if(e)e.oninput=function(){const k=id.substring(1).toLowerCase();S[k]=parseFloat(this.value)||0;upQ()}})
const dF=document.getElementById('dF');if(dF)dF.oninput=function(){S.df=parseFloat(this.value)||0;upQ()}
const mP=document.getElementById('mP');if(mP)mP.oninput=function(){S.mp=parseFloat(this.value)||0;upQ()}
const qty=document.getElementById('qty');if(qty)qty.oninput=function(){S.q=parseInt(this.value)||1;upQ()}
;['pA','pB'].forEach((id,i)=>{const e=document.getElementById(id);if(!e)return;const hId='ah'+(i===0?'A':'B');e.onfocus=function(){const h=document.getElementById(hId);if(h&&S.cu&&S.cu.name&&this.value!==S.cu.name){h.textContent='自动填充: '+S.cu.name;h.classList.add('show')}};e.onblur=function(){setTimeout(()=>{const h=document.getElementById(hId);if(h)h.classList.remove('show')},200)};e.oninput=function(){if(i===0)S.a=this.value;else S.b=this.value;upQ()};document.getElementById(hId).onclick=function(){const v=S.cu&&S.cu.name;if(v){e.value=v;if(i===0)S.a=v;else S.b=v;this.classList.remove('show');upQ()}}})
document.getElementById('addPr').onclick=()=>{S.pr.push({n:'',h:'',u:'时',p:''});rPr()}
document.getElementById('addFee').onclick=()=>{S.fe.push({n:'',a:''});rFe()}
document.getElementById('sBtn').onclick=saveImg;document.getElementById('cBtn').onclick=copyT;document.getElementById('dBtn').onclick=clrD;
// Restore input values, material display, and button states from S after re-render
const ri=(id,val)=>{const e=document.getElementById(id);if(e&&val!==undefined&&val!==null&&val!=='')e.value=val};
ri('pA',S.a);ri('pB',S.b);
ri('dL',S.l);ri('dW',S.w);ri('dH',S.h);
ri('dD',S.d);ri('dH2',S.h2);
ri('mP',S.mp);ri('qty',S.q);ri('dF',S.df);
const md=document.getElementById('mDisp');
if(md){if(S.mt)md.value=S.mt.n+' ('+S.mt.de+'g/cm³)';else md.value=''}
// Restore button active states to match S
if(S.shp==='cylinder'){var s=document.getElementById('shS'),c=document.getElementById('shC'),cd=document.getElementById('cylDims'),sd=document.getElementById('sqDims');if(s)s.classList.remove('active');if(c)c.classList.add('active');if(sd)sd.classList.add('hidden');if(cd)cd.classList.remove('hidden')}
if(S.dl==='send'){var ds=document.getElementById('delSelf'),dn=document.getElementById('delSend'),df=document.getElementById('dfW');if(ds)ds.classList.remove('active');if(dn)dn.classList.add('active');if(df)df.classList.remove('hidden')}
if(S.tx==='yes'){var tn=document.getElementById('taxNo'),ty=document.getElementById('taxYes');if(tn)tn.classList.remove('active');if(ty)ty.classList.add('active')}
upQ()}

function rPr(){const tb=document.getElementById('prB');if(!tb)return;if(S.pr.length===0){tb.innerHTML='<tr><td colspan="7" style="text-align:center;padding:16px;color:#999">暂无工序</td></tr>';return}
tb.innerHTML=S.pr.map((p,i)=>'<tr data-i="'+i+'"><td>'+(i+1)+'</td><td><button class="sPr" style="border:1px solid #2d7aff;color:#2d7aff;background:#f0f4ff;padding:4px 10px;border-radius:6px;font-size:12px" data-i="'+i+'">'+(p.n||'选择工艺')+'</button></td><td><input type="number" class="pH" value="'+(p.h||'')+'" data-i="'+i+'" min="0" step="any"></td><td><select class="pU" data-i="'+i+'"><option value="秒"'+(p.u==='秒'?' selected':'')+'>秒</option><option value="分"'+(p.u==='分'?' selected':'')+'>分</option><option value="时"'+(p.u==='时'?' selected':'')+'>时</option></select></td><td><input type="number" class="pP" value="'+(p.p||'')+'" data-i="'+i+'" min="0" step="any"></td><td><span class="pv">'+cpp(p).toFixed(2)+'</span></td><td><span class="db" data-i="'+i+'">✖</span></td></tr>').join('')
document.querySelectorAll('.sPr').forEach(el=>{el.onclick=function(){showPM(parseInt(this.dataset.i))}})
document.querySelectorAll('.pH').forEach(el=>{el.oninput=function(){S.pr[parseInt(this.dataset.i)].h=this.value;upQ();upPP()}})
document.querySelectorAll('.pU').forEach(el=>{el.onchange=function(){S.pr[parseInt(this.dataset.i)].u=this.value;upQ();upPP()}})
document.querySelectorAll('.pP').forEach(el=>{el.oninput=function(){S.pr[parseInt(this.dataset.i)].p=this.value;upQ();upPP()}})
document.querySelectorAll('#prB .db').forEach(el=>{el.onclick=function(){const i=parseInt(this.dataset.i);scf('是否删除该工序',()=>{S.pr.splice(i,1);rPr();upQ()})}})}
function upPP(){S.pr.forEach((p,i)=>{const c=document.querySelectorAll('#prB tr[data-i="'+i+'"] .pv');if(c.length)c[0].textContent=cpp(p).toFixed(2)})}

function rFe(){const fl=document.getElementById('feeL');if(!fl)return;if(S.fe.length===0){fl.innerHTML='<div style="padding:8px 0;color:#999;font-size:13px">暂无其他费用</div>';return}
fl.innerHTML=S.fe.map((f,i)=>{let n=f.n||'';let a=f.a||'';return'<div class="frow" data-i="'+i+'"><input type="text" class="fN" placeholder="项目名称" value="'+n+'"><input type="number" class="fA" placeholder="费用" value="'+a+'" min="0" step="any"><span class="db" data-i="'+i+'">✖</span></div>'}).join('')
document.querySelectorAll('.fN').forEach(el=>{el.oninput=function(){const i=parseInt(this.parentElement.dataset.i);if(i>=0&&S.fe[i])S.fe[i].n=this.value}})
document.querySelectorAll('.fA').forEach(el=>{el.oninput=function(){const i=parseInt(this.parentElement.dataset.i);if(i>=0&&S.fe[i])S.fe[i].a=this.value;upQ()}})
document.querySelectorAll('#feeL .db').forEach(el=>{el.onclick=function(){const i=parseInt(this.dataset.i);scf('是否删除该费用项',()=>{S.fe.splice(i,1);rFe();upQ()})}})}

function showPM(i){const ov=document.createElement('div');ov.className='mover';ov.style.display='flex';const idx=i
ov.innerHTML='<div class="mbox"><h3>选择工艺</h3><div style="margin-bottom:10px"><input type="text" id="pSch" placeholder="搜索工艺..." style="width:100%;padding:10px 14px;border:1px solid #ddd;border-radius:20px"></div><div id="pT" style="max-height:300px;overflow-y:auto;overflow-x:hidden">'+PROCS.map((g,gi)=>'<div><div class="tcat" data-pg="'+gi+'"><span class="arr" id="pArr'+gi+'">▶</span> '+g.n+'</div><div class="tits" id="pIt'+gi+'">'+g.i.map((p,pi)=>'<div class="tit" data-pg="'+gi+'" data-pi="'+pi+'"><input type="radio" name="pR"> <span>'+p.n+' (¥'+p.p+'/h)</span></div>').join('')+'</div></div>').join('')+'<div class="br" style="margin-top:12px"><button class="btn-o" style="flex:1" id="pmCa">取消</button><button class="btn-p" style="flex:1" id="pmCo">确认</button></div></div>';document.body.appendChild(ov)
// 使用JS事件代理处理工艺展开/折叠
document.querySelectorAll('#pT .tcat').forEach(el=>{el.onclick=function(){const gi=parseInt(this.dataset.pg);togP(gi)}})
// 使用JS事件绑定处理工艺选择
document.querySelectorAll('#pT .tit').forEach(el=>{el.onclick=function(){document.querySelectorAll('#pT input[name="pR"]').forEach(r=>r.checked=false);const r=this.querySelector('input');if(r)r.checked=true;document.getElementById('pSch').dataset.sel=PROCS[parseInt(this.dataset.pg)].i[parseInt(this.dataset.pi)].n+'|'+PROCS[parseInt(this.dataset.pg)].i[parseInt(this.dataset.pi)].p}})
document.getElementById('pmCo').onclick=function(){const sel=document.getElementById('pSch').dataset.sel;if(sel&&idx>=0&&idx<S.pr.length){const p=sel.split('|');S.pr[idx].n=p[0];S.pr[idx].p=parseFloat(p[1])}document.body.removeChild(ov);rPr();upQ()}
document.getElementById('pmCa').onclick=function(){document.body.removeChild(ov)}
document.getElementById('pSch').oninput=function(){const kw=this.value.toLowerCase();document.querySelectorAll('#pT .tit').forEach(el=>{const ok=!kw||el.textContent.toLowerCase().includes(kw);el.style.display=ok?'flex':'none';if(ok&&kw){const p=el.closest('.tits');if(p)p.classList.add('on')}})}}
function togP(i){const e=document.getElementById('pIt'+i),a=document.getElementById('pArr'+i);if(e){e.classList.toggle('on');if(a)a.classList.toggle('on')}}

function saveImg(){if(!checkN())return;const o=gd();sto(o);var el=document.createElement('div');el.innerHTML=buildHTML(o);document.body.appendChild(el);var qp=el.firstChild;html2canvas(qp,{scale:2,backgroundColor:'#fff',useCORS:true}).then(function(c){var d=c.toDataURL('image/png');var w=window.open('');if(w){w.document.write('<div style=\"text-align:center;padding:20px;font-family:sans-serif\"><img src=\"'+d+'\" style=\"max-width:100%;border:1px solid #ddd;border-radius:8px\"><p style=\"margin-top:16px\"><a href=\"'+d+'\" download=\"报价单_'+o.orderId+'.png\" style=\"display:inline-block;padding:12px 24px;background:#2d7aff;color:#fff;text-decoration:none;border-radius:8px;font-size:16px\">⬇ 保存图片（电脑端自动下载，手机端长按保存）</a></p><p style=\"color:#999;font-size:12px;margin-top:8px\">手机端：长按上方图片可保存</p></div>');w.document.close()}else{var a=document.createElement('a');a.href=d;a.download='报价单_'+o.orderId+'.png';document.body.appendChild(a);a.click();document.body.removeChild(a)}document.body.removeChild(el);tst('已保存','ok')}).catch(function(){document.body.removeChild(el);tst('保存失败','warn')})}function copyT(){if(!checkN())return;const o=gd();sto(o);let t='工价计算器报价单\n编号：'+S.no+'\n日期：'+S.date+'\n甲方：'+(S.a||'—')+'\n乙方：'+(S.b||'—')+'\n';t+='\n【材料费用】\n';if(S.mt)t+='材料：'+S.mt.n+' ('+S.mt.de+'g/cm³)\n';t+='尺寸：'+(S.shp==='square'?S.l+'×'+S.w+'×'+S.h+'mm':'直径'+S.d+'×高'+S.h2+'mm')+'\n';t+='数量：'+S.q+'件\n单价：'+parseFloat(S.mp).toFixed(2)+'元/kg\n总材料成本：'+ctm().toFixed(2)+'元\n';t+='\n【加工工序】\n';if(S.pr.length===0)t+='无\n';else S.pr.forEach(p=>{t+=(p.n||'未选择')+' | '+(p.h||0)+'h × ¥'+parseFloat(p.p||0).toFixed(2)+' = '+cpp(p).toFixed(2)+'元\n'});t+='\n【其他费用】\n';if(S.dl==='send')t+='运费：'+parseFloat(S.df).toFixed(2)+'元\n';S.fe.filter(f=>f.n).forEach(f=>{t+=(f.n||'')+'：'+parseFloat(f.a||0).toFixed(2)+'元\n'});t+='税：'+(S.tx==='yes'?'已含13%增值税':'未含税')+'\n';t+='\n总价：¥ '+ctot().toFixed(2)+'\n—本报价单由「工价计算器」生成，仅供参考—';navigator.clipboard.writeText(t).then(()=>tst('已复制到剪贴板','ok')).catch(()=>tst('复制失败','warn'))}
function clrD(){scf('清除所有数据？此操作不可撤销。',()=>{S.shp='square';S.l='';S.w='';S.h='';S.d='';S.h2='';S.mt=null;S.mp='';S.q=1;S.pr=[];S.dl='self';S.df='';S.tx='no';S.fe=[];rA()})}
function checkN(){const aE=document.getElementById('nA'),bE=document.getElementById('nB');if(aE)aE.classList.remove('show');if(bE)bE.classList.remove('show');let ok=true
if(!S.a||!S.b){let msg='提醒：';if(!S.a)msg+='甲方';if(!S.a&&!S.b)msg+='、';if(!S.b)msg+='乙方';msg+='名称未填写';scf(msg,()=>{if(!S.a&&aE){aE.textContent='未填写名称';aE.classList.add('show')}if(!S.b&&bE){bE.textContent='未填写名称';bE.classList.add('show')}document.querySelector('.phdr')?.scrollIntoView({behavior:'smooth'})});ok=false}
if(ok&&S.a===S.b){scf('提醒：甲方与乙方名称相同',()=>{if(aE){aE.textContent='名称相同';aE.classList.add('show')}if(bE){bE.textContent='名称相同';bE.classList.add('show')}document.querySelector('.phdr')?.scrollIntoView({behavior:'smooth'})});ok=false}return ok}
function buildHTML(o){const m=o.material,d=o.dimensions||{};
function cw2(){if(!m)return 0;let v=0;if(o.shape==='square')v=(parseFloat(d.l)||0)*(parseFloat(d.w)||0)*(parseFloat(d.h)||0);else v=Math.PI*((parseFloat(d.d)||0)/2)**2*(parseFloat(d.h2||d.h)||0);return(v/1000)*m.de/1000}
function cm2(){return cw2()*(parseFloat(o.materialPrice)||0)*(parseInt(o.quantity)||1)}
function cp2(p){let h=parseFloat(p.hours||p.h)||0;if((p.unit||p.u)==='秒')h/=3600;else if((p.unit||p.u)==='分')h/=60;return h*(parseFloat(p.price||p.p)||0)}
return'<div style="background:#fff;padding:24px;font-family:\'PingFang SC\',Arial;max-width:500px;margin:0 auto;border:2px solid #e0e0e0;border-radius:12px;color:#333"><h2 style="text-align:center;font-size:18px;color:#2d7aff;margin-bottom:10px">工价计算器报价单</h2><hr style="border:0;border-top:1px solid #e0e0e0;margin:8px 0">'+
'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>甲方</span><span>'+(o.clientName||'—')+'</span></div><div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>乙方</span><span>'+(o.ourCompany||'—')+'</span></div><div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>编号</span><span>'+o.orderId+'</span></div><div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>日期</span><span>'+(o.date||'')+'</span></div><hr style="border:0;border-top:1px solid #e0e0e0;margin:8px 0">'+
'<div style="display:flex;align-items:center;gap:6px;font-size:14px;font-weight:700;margin:10px 0 6px;color:#2d7aff;border-left:3px solid #2d7aff;padding-left:10px">📦 材料费用</div>'+(m?'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>材料类型</span><span>'+m.n+' ('+m.de+'g/cm³)</span></div>':'')+
'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>尺寸</span><span>'+(o.shape==='square'?'长'+(d.l||0)+'mm×宽'+(d.w||0)+'mm×高'+(d.h||0)+'mm':'直径'+(d.d||0)+'mm×高'+(d.h2||0)+'mm')+'</span></div><div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>数量</span><span>'+(o.quantity||1)+' 件</span></div><div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>单价</span><span>'+parseFloat(o.materialPrice||0).toFixed(2)+' 元/kg</span></div><div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>材料总成本</span><span>'+cm2().toFixed(2)+' 元</span></div><hr style="border:0;border-top:1px solid #e0e0e0;margin:8px 0">'+
'<div style="display:flex;align-items:center;gap:6px;font-size:14px;font-weight:700;margin:10px 0 6px;color:#2d7aff;border-left:3px solid #2d7aff;padding-left:10px">⚙️ 加工工序</div>'+(o.processes&&o.processes.length>0?o.processes.map(p=>'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>'+(p.procName||p.n||'未选择')+'</span><span>'+(p.hours||p.h||0)+'h×'+parseFloat(p.price||p.p||0).toFixed(2)+'='+cp2(p).toFixed(2)+'元</span></div>').join(''):'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>无</span><span></span></div>')+
'<hr style="border:0;border-top:1px solid #e0e0e0;margin:8px 0"><div style="display:flex;align-items:center;gap:6px;font-size:14px;font-weight:700;margin:10px 0 6px;color:#2d7aff;border-left:3px solid #2d7aff;padding-left:10px">💰 其他费用</div>'+(o.delivery==='send'?'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>运费</span><span>'+parseFloat(o.shippingFee||o.deliveryFee||0).toFixed(2)+' 元</span></div>':'')+(o.extraItems||[]).filter(f=>f.name||f.fee||f.n||f.a).map(f=>'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>'+(f.name||f.n||'其他')+'</span><span>'+parseFloat(f.fee||f.a||f.amount||0).toFixed(2)+' 元</span></div>').join('')+
'<div style="display:flex;justify-content:space-between;padding:3px 0;font-size:13px"><span>税</span><span>'+(o.taxIncluded?'已含13%增值税':'未含税')+'</span></div><hr style="border:0;border-top:1px solid #e0e0e0;margin:8px 0"><div style="text-align:right;font-size:20px;font-weight:800;margin:8px 0 4px;color:#333">总价: ¥ <span style="color:#2d7aff">'+(o.totalPrice?o.totalPrice.toFixed(2):'0.00')+'</span></div><div style="text-align:center;font-size:10px;color:#999;margin-top:8px">本报价单由「工价计算器」生成，仅供参考</div></div>'}

/* 历史订单 */
function rH(){return'<div class="card"><div class="ct">历史订单</div><div class="hcnt" id="hCt">共 0 条历史订单</div><div style="display:flex;gap:8px;margin-bottom:14px"><input type="text" id="hSch" placeholder="甲方名称 / 编号 / 日期" style="flex:1"><button class="btn btn-sm btn-p" id="hBtn">查找</button></div><div id="hL"></div><div class="pw" id="hPw"></div></div>'}
function fO(os,kw){if(!kw.trim())return os;kw=kw.trim().toLowerCase();let pts=kw.split(/[\s,，]+/);if(pts.length>=2){let nP=pts.find(p=>/[一-龥]/.test(p))||'',dP=pts.find(p=>/[\d\.月\/]/.test(p))||'';return os.filter(o=>{let mn=!nP||(o.clientName||'').toLowerCase().includes(nP)||(o.ourCompany||'').toLowerCase().includes(nP);let md=true;if(dP){let m=dP.match(/(\d+)[\.月\/](\d+)/);if(m){let t=td().slice(0,4)+'-'+m[1].padStart(2,'0')+'-'+m[2].padStart(2,'0');md=o.date===t}else md=false}return mn&&md})}let iD=/(\d+)[\.月\/](\d+)/.test(kw);if(iD){let m=kw.match(/(\d+)[\.月\/](\d+)/);if(m){let t=td().slice(0,4)+'-'+m[1].padStart(2,'0')+'-'+m[2].padStart(2,'0');return os.filter(o=>o.date===t)}}return os.filter(o=>(o.orderId||'').toLowerCase().includes(kw)||(o.clientName||'').toLowerCase().includes(kw)||(o.ourCompany||'').toLowerCase().includes(kw))}
function sO(os){return[...os].sort((a,b)=>{if(a.saveTime!==b.saveTime)return new Date(b.saveTime)-new Date(a.saveTime);let sa=[...a.clientName].filter(c=>c>'一'&&c<'鿿').length,sb=[...b.clientName].filter(c=>c>'一'&&c<'鿿').length;return sa-sb||new Date(b.saveTime)-new Date(a.saveTime)})}
function rHL(){const os=lo(),fi=fO(os,hS),so=sO(fi),tl=so.length;const cnt=document.getElementById('hCt');if(cnt)cnt.textContent='共 '+tl+' 条历史订单';const st=(hP-1)*pS,pg=so.slice(st,st+pS);const li=document.getElementById('hL');if(!li)return;if(pg.length===0){li.innerHTML='<div class="he">暂无历史订单</div>'}else{li.innerHTML=pg.map((o,i)=>{const idx=st+i+1;const mn=o.material?o.material.n+'×'+o.quantity:'',tp=o.totalPrice?o.totalPrice.toFixed(2):'0.00';return'<div class="hcard"><div class="hIdx" style="width:28px;font-size:12px;font-weight:700;color:#2d7aff;flex-shrink:0;text-align:center">'+idx+'</div><div class="hl"><div class="hn">'+(o.clientName||'未填')+'</div><div class="hm">编号：'+o.orderId+'</div><div class="hm">日期：'+(o.date||'')+'</div><div class="hp">¥ '+tp+'</div>'+(mn?'<div class="hm">材料：'+mn+'</div>':'')+'</div><div class="ha"><button class="btn btn-sm btn-p" onclick="viewO(\''+o.orderId+'\')">查看</button><button class="btn btn-sm btn-d" onclick="delO(\''+o.orderId+'\')">删除</button></div></div>'}).join('')}rPw(tl)}
function rPw(tl){const wr=document.getElementById('hPw');if(!wr)return;const pg=Math.ceil(tl/pS);if(pg<=1||tl===0){wr.innerHTML='';return}wr.innerHTML='<button onclick="hP=1;rHL()"'+(hP===1?' disabled':'')+'>首页</button><button onclick="hP='+Math.max(1,hP-1)+';rHL()"'+(hP===1?' disabled':'')+'>上一页</button><span class="pi">第'+hP+'/共'+pg+'页</span><button onclick="hP='+Math.min(pg,hP+1)+';rHL()"'+(hP===pg?' disabled':'')+'>下一页</button><button onclick="hP='+pg+';rHL()"'+(hP===pg?' disabled':'')+'>末页</button>'}
function delO(id){scf('是否删除该订单？',()=>{let os=lo();os=os.filter(x=>x.orderId!==id);so(os);rHL()})}
function viewO(id){const os=lo(),o=os.find(x=>x.orderId===id);if(!o)return;const ov=document.createElement('div');ov.className='mover';ov.style.display='flex'
const el=document.createElement('div');el.innerHTML=buildHTML(o);const ct=el.firstChild;ct.style.maxWidth='520px';ct.style.margin='0 auto'
ov.innerHTML='<div style="display:flex;flex-direction:column;width:100%;max-width:560px;margin:auto;max-height:90vh"><div class="mbox" style="max-width:560px;flex:1;overflow-y:auto;border-radius:14px 14px 0 0;padding:24px 20px 16px"><div id="detC"></div></div><div style="background:#fff;border-radius:0 0 14px 14px;overflow:hidden"><button class="btn-p" id="dSv" style="width:50%;padding:13px 0;border-radius:0;float:left;font-size:14px">💾 一键保存</button><button class="btn-o" id="dCp" style="width:50%;padding:13px 0;border-radius:0;float:left;font-size:14px;border:none;border-left:1px solid #eee">📋 一键复制</button></div><button class="btn-p" id="dCl" style="width:100%;padding:13px 0;border-radius:0 0 14px 14px;font-size:14px;background:#999;flex-shrink:0;border:none">关闭</button></div>'
document.body.appendChild(ov);const dc=document.getElementById('detC');if(dc)dc.appendChild(ct.cloneNode(true))
document.getElementById('dSv').onclick=()=>{const el2=document.createElement('div');el2.innerHTML=buildHTML(o);document.body.appendChild(el2);const qp2=el2.firstChild;html2canvas(qp2,{scale:2,backgroundColor:'#fff',useCORS:true}).then(c2=>{const d2=c2.toDataURL('image/png');const w2=window.open('');if(w2){w2.document.write('<div style=\"text-align:center;padding:20px;font-family:sans-serif\"><img src=\"'+d2+'\" style=\"max-width:100%;border:1px solid #ddd;border-radius:8px\"><p style=\"margin-top:16px\"><a href=\"'+d2+'\" download=\"报价单_'+o.orderId+'.png\" style=\"display:inline-block;padding:12px 24px;background:#2d7aff;color:#fff;text-decoration:none;border-radius:8px;font-size:16px\">⬇ 保存图片（电脑端自动下载，手机端长按保存）</a></p><p style=\"color:#999;font-size:12px;margin-top:8px\">手机端：长按上方图片可保存</p></div>');w2.document.close()}else{const a2=document.createElement('a');a2.href=d2;a2.download='报价单_'+o.orderId+'.png';document.body.appendChild(a2);a2.click();document.body.removeChild(a2)}document.body.removeChild(el2);tst('已保存','ok')}).catch(()=>{document.body.removeChild(el2);tst('保存失败','warn')})}
document.getElementById('dCp').onclick=()=>{const m=o.material,d=o.dimensions||{};let t='工价计算器报价单\n编号：'+o.orderId+'\n日期：'+(o.date||'')+'\n甲方：'+(o.clientName||'—')+'\n乙方：'+(o.ourCompany||'—')+'\n';t+='\n【材料费用】\n';if(m)t+='材料：'+m.n+' ('+m.de+'g/cm³)\n';t+='尺寸：'+(o.shape==='square'?(d.l||0)+'×'+(d.w||0)+'×'+(d.h||0)+'mm':'直径'+(d.d||0)+'×高'+(d.h2||0)+'mm')+'\n';t+='数量：'+(o.quantity||1)+'件\n材料总成本：'+(o.totalPrice?o.totalPrice.toFixed(2):'0.00')+'元\n';t+='\n【加工工序】\n';if(!o.processes||o.processes.length===0)t+='无\n';else o.processes.forEach(p=>{t+=(p.procName||p.n||'未选择')+' | '+(p.hours||p.h||0)+'h×¥'+parseFloat(p.price||p.p||0).toFixed(2)+'='+(p.hours||p.h||0)*parseFloat(p.price||p.p||0).toFixed(2)+'元\n'});t+='\n【其他费用】\n';if(o.delivery==='send')t+='运费：'+parseFloat(o.shippingFee||o.deliveryFee||0).toFixed(2)+'元\n';(o.extraItems||[]).filter(f=>f.name||f.fee||f.n||f.a).forEach(f=>{t+=(f.name||f.n||'其他')+'：'+parseFloat(f.fee||f.a||f.amount||0).toFixed(2)+'元\n'});t+='税：'+(o.taxIncluded?'已含13%增值税':'未含税')+'\n';t+='\n总价：¥ '+(o.totalPrice?o.totalPrice.toFixed(2):'0.00')+'\n—本报价单由「工价计算器」生成，仅供参考—';navigator.clipboard.writeText(t).then(()=>tst('已复制到剪贴板','ok')).catch(()=>tst('复制失败','warn'))}
document.getElementById('dCl').onclick=()=>document.body.removeChild(ov);ov.addEventListener('click',e=>{if(e.target===ov)document.body.removeChild(ov)})}

/* 我的页面 */
function initP(){document.getElementById('eNm').onclick=editName;document.getElementById('cUID').onclick=copyUID;document.getElementById('pAuth').onclick=()=>tst('因隐私问题，该功能正在开放中...','warn');document.getElementById('pEnt').onclick=()=>tst('因隐私问题，该功能正在开放中...','warn');document.getElementById('pPwd').onclick=showPwdM;document.getElementById('pUpd').onclick=()=>tst('当前已是最新版本','ok');document.getElementById('pChangelog').onclick=showChangelog;document.getElementById('pAbout').onclick=showAbout;document.getElementById('pFb').onclick=showFb;document.getElementById('pLo').onclick=showLo}
function rP(){const u=S.cu||{uid:'',name:''},inl=(u.name||u.uid||'?')[0]
return'<div class="card"><div class="pav"><div class="pc">'+inl+'</div></div><div class="pnm"><span id="pNm">'+(u.name||'')+'</span><button class="eb" id="eNm">✏️</button></div><div class="puid"><span>UID: '+(u.uid||'')+'</span><button class="cb" id="cUID">📋</button></div></div><div class="card"><div class="psec">'+
'<div class="pitem" id="pAuth"><div class="pil"><svg viewBox="0 0 24 24"><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg><span>个人认证</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pEnt"><div class="pil"><svg viewBox="0 0 24 24"><path d="M12 7V3H2v18h20V7H12z"/></svg><span>企业认证</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pPwd"><div class="pil"><svg viewBox="0 0 24 24"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2z"/></svg><span>修改密码</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pUpd"><div class="pil"><svg viewBox="0 0 24 24"><path d="M17.65 6.35C16.2 4.9 14.21 4 12 4c-4.42 0-7.99 3.58-7.99 8s3.57 8 7.99 8c3.73 0 6.84-2.55 7.73-6h-2.08c-.82 2.33-3.04 4-5.65 4-3.31 0-6-2.69-6-6s2.69-6 6-6c1.66 0 3.14.69 4.22 1.78L13 11h7V4l-2.35 2.35z"/></svg><span>检查更新</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pChangelog"><div class="pil"><svg viewBox="0 0 24 24"><path d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm-3 16H7v-2h4v2zm6-4H7v-2h10v2zm0-4H7V8h10v2z"/></svg><span>更新日志</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pAbout"><div class="pil"><svg viewBox="0 0 24 24"><path d="M11 17h2v-6h-2v6zm1-15C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z"/></svg><span>关于我们</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pFb"><div class="pil"><svg viewBox="0 0 24 24"><path d="M20 2H4c-1.1 0-1.99.9-1.99 2L2 22l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2z"/></svg><span>问题反馈</span></div><div class="pir"><span>></span></div></div>'+
'<div class="pitem" id="pLo"><div class="pil"><svg viewBox="0 0 24 24"><path fill="#ff4757" d="M17 7l-1.41 1.41L18.17 11H8v2h10.17l-2.58 2.58L17 17l5-5zM4 5h8V3H4c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h8v-2H4V5z"/></svg><span style="color:#ff4757">退出登录</span></div><div class="pir"><span>></span></div></div>'+
'</div></div><div class="pver">V2.2.2</div>'}
function editName(){const n=S.cu.name||'',ov=document.createElement('div');ov.className='mover';ov.style.display='flex';ov.innerHTML='<div class="mbox"><h3>更改名称</h3><div class="f"><label>用户名</label><input type="text" id="nmI" value="'+es(n)+'" placeholder="输入新名称"></div><div class="br"><button class="btn-o" id="nmCa">取消</button><button class="btn-p" id="nmSv">保存</button></div></div>';document.body.appendChild(ov)
document.getElementById('nmCa').onclick=()=>document.body.removeChild(ov)
document.getElementById('nmSv').onclick=()=>{const v=document.getElementById('nmI').value.trim();if(v){const us=lu();if(us[S.cu.uid]){us[S.cu.uid].name=v;S.cu.name=v;su(us)}document.getElementById('pNm').textContent=v;const pc=document.querySelector('.pc');if(pc)pc.textContent=(v||S.cu.uid||'?')[0]}document.body.removeChild(ov)}}
function copyUID(){navigator.clipboard.writeText(S.cu.uid||'').then(()=>tst('已复制UID，请妥善保管！','ok'))}

var capA=0,capB=0,capOp='+',capAns=0;function genCap(){var ops=['+','-','×','÷'];capOp=ops[Math.floor(Math.random()*4)];if(capOp==='×'){capA=Math.floor(Math.random()*9+1);capB=Math.floor(Math.random()*9+1);capAns=capA*capB}else if(capOp==='÷'){capB=Math.floor(Math.random()*8+2);capA=capB*(Math.floor(Math.random()*8+2));capAns=capA/capB}else{capA=Math.floor(Math.random()*20+1);capB=Math.floor(Math.random()*20+1);if(capOp==='-'){if(capA<capB){var t=capA;capA=capB;capB=t}capAns=capA-capB}else capAns=capA+capB}var q=document.getElementById('capQ');if(q)q.textContent=capA+' '+capOp+' '+capB+' = ?';var i=document.getElementById('capI');if(i)i.value='';var e=document.getElementById('capE');if(e)e.textContent=''}
function showPwdM(){const ov=document.createElement('div');ov.className='mover';ov.style.display='flex';ov.innerHTML='<div class="mbox"><h3>修改密码</h3><div class="f"><label>原密码</label><div class="iw"><input type="password" id="oP" placeholder="原密码"><button class="pwt" id="oPT">👁</button></div></div><div class="f"><label>新密码</label><div class="iw"><input type="password" id="nP" placeholder="输入新密码（至少6位，字母/数字）"><button class="pwt" id="nPT">👁</button></div></div><div class="lerr" id="pwdE" style="min-height:20px"></div><div class="br"><button class="btn-o" id="pwdCa">取消</button><button class="btn-p" id="pwdSv">保存</button></div></div>';document.body.appendChild(ov)
document.getElementById('pwdCa').onclick=()=>document.body.removeChild(ov)
document.getElementById('pwdSv').onclick=()=>{const old=document.getElementById('oP').value,np=document.getElementById('nP').value,err=document.getElementById('pwdE');const us=lu();if(us[S.cu.uid].pwd!==old){err.textContent='原密码错误';return}if(np===old){err.textContent='新密码不能与原密码一致';return}if(!/^[A-Za-z0-9]{6,}$/.test(np)){err.textContent='密码至少6位，字母/数字';return}us[S.cu.uid].pwd=np;S.cu.pwd=np;su(us);tst('密码修改成功','ok');document.body.removeChild(ov)};document.getElementById('oPT').onclick=function(){const i=document.getElementById('oP');if(i.type==='password'){i.type='text';this.textContent='🙈'}else{i.type='password';this.textContent='👁'}};document.getElementById('nPT').onclick=function(){const i=document.getElementById('nP');if(i.type==='password'){i.type='text';this.textContent='🙈'}else{i.type='password';this.textContent='👁'}}}
function showChangelog(){const ov=document.createElement('div');ov.className='mover';ov.style.display='flex';ov.style.overflow='hidden';ov.innerHTML='<div style="position:relative;width:100%;max-width:520px;margin:0 auto"><div class="mbox" style="max-height:70vh;overflow-y:auto;padding-bottom:20px"><h3>更新日志</h3><div class="clog" style="font-size:13px;color:#333;line-height:1.7">'+
'<div style="background:#f8f9fb;border-radius:10px;padding:12px 14px;margin-bottom:12px"><div style="font-size:15px;font-weight:700;color:#2d7aff;margin-bottom:6px">V2.2.2</div><div style="font-size:12px;color:#999;margin-bottom:6px">品牌升级 · 云端同步 · 体验优化</div>• 【新增】柔光粒子背景动画，登录/注册页淡蓝色光点缓慢上浮<br>• 【新增】品牌视觉升级：顶部图标黑.png、底部logo.png、标题渐流动画<br>• 【新增】注册页算术验证码，防机器注册<br>• 【新增】腾讯云CloudBase云端数据同步，多设备自动合并<br>• 【新增】密码输入框眼睛图标👁/🙈切换，密码可视化控制<br>• 【新增】手机端保存报价单：新窗口展示图片，支持长按保存<br>• 【修复】rL函数缺失闭合括号导致页面空白的严重bug<br>• 【修复】甲方/乙方名称输入时报价单预览未实时同步的问题<br></div>'+
'<div style="background:#f8f9fb;border-radius:10px;padding:12px 14px;margin-bottom:12px"><div style="font-size:15px;font-weight:700;color:#2d7aff;margin-bottom:6px">V2.2.1</div><div style="font-size:12px;color:#999;margin-bottom:6px">视觉与交互细节优化</div>• 【新增】登录页标题渐变动画效果<br>• 【新增】甲方/乙方输入框自动填充用户名提示（基于登录用户名）<br>• 【优化】输入框placeholder缩短，适配手机端避免文字截断<br>• 【修复】修改用户名后头像首字母未即时更新的问题<br>• 【新增】更新日志弹窗，版本化展示历史更新<br></div>'+
'<div style="background:#f8f9fb;border-radius:10px;padding:12px 14px;margin-bottom:12px"><div style="font-size:15px;font-weight:700;color:#2d7aff;margin-bottom:6px">V2.2.0</div><div style="font-size:12px;color:#999;margin-bottom:6px">核心稳定性修复</div>• 【修复】材料成本始终显示为0的问题（属性大小写bug）<br>• 【修复】方形/圆柱形按钮active状态视觉切换无效的问题<br>• 【修复】自提/运送、含税按钮点击后样式无变化的问题<br>• 【修复】工艺选择弹窗HTML引号嵌套导致内容显示错乱的问题<br>• 【优化】输入框去除硬编码value="0"，点击即输，提升输入体验<br>• 【优化】Tab切换后自动恢复输入数据和按钮激活状态<br>• 【优化】方形/圆柱形切换逻辑：尺寸输入互斥显示<br>• 【优化】工艺选择弹窗隐藏水平滚动条<br>• 【新增】Tab图标更新（工价计算齿轮图标、历史订单笔记本图标）<br>• 【新增】历史订单倒序编号<br></div>'+
'<div style="background:#f8f9fb;border-radius:10px;padding:12px 14px;margin-bottom:12px"><div style="font-size:15px;font-weight:700;color:#2d7aff;margin-bottom:6px">V2.1.0</div><div style="font-size:12px;color:#999;margin-bottom:6px">功能新增与完善</div>• 【新增】方形/圆柱形切换时尺寸输入框动态切换功能<br>• 【新增】按钮点击时视觉反馈（active状态样式变化）<br>• 【完善】历史订单搜索功能，支持按甲方名称/编号/日期组合搜索<br>• 【优化】历史订单排序逻辑<br>• 【优化】工价计算页面输入框布局<br></div>'+
'<div style="background:#f8f9fb;border-radius:10px;padding:12px 14px;margin-bottom:12px"><div style="font-size:15px;font-weight:700;color:#2d7aff;margin-bottom:6px">V2.0.0</div><div style="font-size:12px;color:#999;margin-bottom:6px">重大更新内容</div>• 【重构】用户体系，新增UID登录与注册功能，支持账号持久化<br>• 【新增】底部导航栏（TabBar），页面拆分为"工价计算""历史订单""我的"三个独立板块<br>• 【新增】历史订单功能独立为二级页面，支持独立查看与管理，不再以弹窗形式展示<br>• 【新增】"我的"个人中心页面，集成用户名修改、密码修改、关于我们、问题反馈等功能<br>• 【新增】一键清除全部数据功能<br>• 【新增】甲方/乙方名称填写及冲突提醒机制<br>• 【优化】报价单预览动态更新，实时反映当前输入数据<br>• 【新增】密码可视化切换（显示/隐藏）功能<br></div>'+
'</div></div><div style="text-align:center;margin-top:10px"><span id="clC" style="font-size:28px;cursor:pointer;color:#999;display:inline-block;width:44px;height:44px;line-height:44px;border-radius:50%;background:rgba(255,255,255,.9)">✕</span></div></div>';document.body.appendChild(ov);document.getElementById('clC').onclick=()=>document.body.removeChild(ov);ov.addEventListener('click',e=>{if(e.target===ov)document.body.removeChild(ov)})}
function showAbout(){const ov=document.createElement('div');ov.className='mover';ov.style.display='flex';ov.innerHTML='<div class="mbox"><h3>关于我们</h3><div style="font-size:13px;line-height:1.8;color:#666">工价计算器是一款面向中小型机械加工企业的智能化报价辅助工具，服务对象涵盖机床加工、模具制造、五金制品、零部件生产等制造行业。旨在解决传统报价模式中过度依赖技术人员个人经验、流程效率低下、历史数据无法有效复用等长期存在的行业痛点。通过材料成本自动核算、工序费用动态计算、历史订单云端存储与多维度检索等功能，协助企业实现从经验驱动到数据驱动的报价管理模式转变，降低技术门槛，提升经营效率，促进隐性知识的数字化沉淀与传承。<br><br>本应用项目由重庆外语外事学院智能科学与工程学院「拉普拉斯（Laplace）」项目小组研发。<br><br>联系我们：taylorcg@qq.com</div><div class="br" style="margin-top:16px"><button class="btn-p" style="flex:1" id="abC">关闭</button></div></div>';document.body.appendChild(ov);document.getElementById('abC').onclick=()=>document.body.removeChild(ov);ov.addEventListener('click',e=>{if(e.target===ov)document.body.removeChild(ov)})}
function showFb(){const ov=document.createElement('div');ov.className='mover';ov.style.display='flex';ov.innerHTML='<div class="mbox"><h3>问题反馈</h3><div style="font-size:14px;color:#666;text-align:center;padding:10px 0 20px;line-height:1.6">若您在使用过程中有遇到问题或有更好建议，烦请发至邮箱：<br><a href="mailto:taylorcg@qq.com" style="color:#2d7aff;text-decoration:none;font-weight:600">taylorcg@qq.com</a></div><div style="text-align:center"><span id="fbC" style="font-size:28px;cursor:pointer;color:#999;display:inline-block;width:44px;height:44px;line-height:44px;border-radius:50%">✕</span></div></div>';document.body.appendChild(ov);document.getElementById('fbC').onclick=()=>document.body.removeChild(ov);ov.addEventListener('click',e=>{if(e.target===ov)document.body.removeChild(ov)})}
function showLo(){const ov=document.createElement('div');ov.className='mover';ov.style.display='flex';ov.innerHTML='<div class="mbox"><h3>是否退出当前账号</h3><div class="rt">请妥善保管UID</div><div class="br"><button class="btn-o" id="lgN">否</button><button class="btn-d" id="lgY">是</button></div></div>';document.body.appendChild(ov);document.getElementById('lgN').onclick=()=>document.body.removeChild(ov);document.getElementById('lgY').onclick=()=>{S.lg=false;S.cu=null;document.body.removeChild(ov);localStorage.removeItem('au');rL()}}

try{(function(){const au=la();if(au){const us=lu();if(us[au]){S.cu=us[au];S.cu.uid=au;S.lg=true}}r()})();}catch(e){document.getElementById('app').innerHTML='<div style="padding:20px;text-align:center;color:red">Error: '+e.message+' at line '+e.lineNumber+'</div>'}
